name: Build & Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          node-version: 20

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          cd dist
          zip -r site.zip .

      - name: Upload zip & Unzip
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            # 备份旧文件
            cp -r /home/ubuntu/qq-farm-bot /home/ubuntu/qq-farm-bot.bak.$(date +%Y%m%d_%H%M%S)
            # 清空目录
            rm -rf /home/ubuntu/qq-farm-bot/*
            # 解压
            cd /home/ubuntu/qq-farm-bot
            unzip -o ~/site.zip
            # 删除压缩包
            rm -f ~/site.zip
          scp: |
            dist/site.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/site.zip
